name: Terraform Pipeline

on:
  push:
    branches:
      - main
      - feature/practice

  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./env/prod
        run: terraform init

      - name: Terraform Format
        working-directory: ./env/prod
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./env/prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./env/prod
        run: terraform plan 